name: koregraph

services:
  mlflow:
    image: europe-west1-docker.pkg.dev/le-wagon-420414/koregraph/koregraph-mlflow:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./data:/mlflow"
      - "./mlruns:/mlruns"
    environment:
      BACKEND_URI: sqlite:////mlflow/mlflow.db
      ARTIFACT_ROOT: /mlflow/artifacts
